- README.md
- api/Dockerfile.api
- api/main.py
- api/requirements.txt
- api/utils/convert.py
- api/utils/download.py
- api/utils/generate.py
- docker-compose.yml
This PR ads an autodownload script that fetches the model weights from huggingface. This simplifies the initial setup of Serge to just :
```
git clone git@github.com:nsarrazin/serge.git && cd serge
cp .env.sample .env
docker compose up -d
docker compose exec api python3 /usr/src/app/utils/download.py tokenizer 7B
```
This also adds support for the 30B theoretically, although I haven't tried it.
This PR closes #2, #13
> Add an auto-download script that supports 7B, 13B & 30B models

- api/main.py
- api/requirements.txt
Fixes #12 
If endpoints requiring models are called before the initialization is done, a 503 error is returned
Note that additional checks could be added to `dep_models_ready()` to ensure the bin file and weight are present
> do not block server while initializing models

- Dockerfile
gcc12 doesn't work when running make on M1 mac
> Update Dockerfile to enable llama build on M1 mac

- .github/workflows/docker-image.yml
this is better than a release branch
> run the image deployment process when a release is published

- .github/dependabot.yml
- .github/workflows/docker-image.yml
Changes:
- Added support for building both `linux/amd64` and `linux/arm64`
- Added support for creating Docker tags for: main, latest and semver major and minor versions.
- Support for running Docker Build for each PR.
- Support for dependabot to upgrade github-actions. In the future Docker, npm and pypi can be added.
- Added the cache changes from #70 
Good to know:
- Changes to `main` will update the Docker tags: `main` and `latest`.
- New releases will create Docker images for semver and `latest` tag.
- All PR's will trigger the CI, but will not publish new images.
Next Steps:
- Delete the `release` branch.
> Improvements to github actions

- Dockerfile
- compile.sh
- deploy.sh
- dev.sh
Currently compiling llama.cpp has to be done on the user's CPU, that means using github workers is out of the question. More about the issue here: https://github.com/nsarrazin/serge/issues/82
So as a workaround, the llama binary is created when the image is started up. This is a bit silly and feels wrong but it should make our released images usable.
> Move the llama.cpp compilation step to after the image is built

- README.md
just I catch a typo on the Readme
> docs: correct the name 7B-native on Readme

- web/src/routes/+page.svelte
Working on https://github.com/nsarrazin/serge/issues/133
In the view it was named `ctx_length` but the controller expected `context_window`
- Update name to `context_window`
> Correctly pass the context window length

- web/src/routes/chat/[id]/+page.svelte
Made to address #135 
This allows for a "New" button which takes all of the current sessions parameters and creates a new session. 
When the new session is provided by the API we then redirect to the new session ID. 
To make things easy on users, a new hotkey was set up to allow for the use of ALT+N which will create a new session on demand.
> Adding a new session button which uses current session settings

- .github/dependabot.yml
- .github/workflows/docker-image.yml
- Adds support for tracking `npm`, `pip`, and `docker` dependencies.
> Expand dependabot coverage

- web/src/routes/+page.svelte
The name of the parameter is `temperature` in the API, but this form passes it as `temp`, so all invocations of `llama` always use a temperature of 0.1 (the default value in the API) regardless of this setting.
> Fixed name of the temperature parameter

- api/src/serge/routers/model.py
Fixes issue #295. 
I tested the updated files. They both download and run with the current version of serge/llama used by serge.
> update names of vicuna models, fixes #295

- .github/workflows/docker-image.yml
- Only updates the latest tag when a new release is created 
This will allow testing merges to the main branch
> Don't update latest tag when merging to default brancv

- README.md
- api/src/serge/routers/model.py
- scripts/deploy.sh
This PR pins llama-cpp-python in the Docker image to 0.1.54 so newer models like Guanaco work. This breaks compatibility for GGMLv2 models (a decision made by llama.cpp developers). It may be a good idea to keep a branch of Serge that supports GGMLv2.
> GGMLv3 support

- api/src/serge/routers/chat.py
The answer coming back fron `llama` can be anything, enforce a String when returning to API Client
Fixes #259
> Make sure answer is a string when returning to API Client

- Dockerfile
- api/src/serge/data/models.json
- Both llama.cpp and llama-cpp-python have issues compiling with Debian 12. Lets pin the image to debian-11 until a fix is found.
- Update models.json
Fixes #453
> Update models.json and change Docker base images to Debian 11

- .dockerignore
- .gitignore
- Dockerfile
- Dockerfile.dev
- README.md
- api/test/healthcheck_models.py
- config/redis.conf
- docker-compose.dev.yml
- Added separate Dockerfile for doing development
- Refactored some of the commands used in the Dockerfile
- Removed the need for BUILDKIT when doing local dev
- Added more rules to gitignore/dockerignore
> Refactor production Dockerfile, Add development Dockerfile

- scripts/deploy.sh
- Bump llama-cpp-python bindings to v0.1.69
- This brings support for newest fastapi/pydantic
> Support for llama-cpp-python v0.1.69

- Dockerfile
- Dockerfile.dev
- README.md
- scripts/deploy.sh
- scripts/dev.sh
- Remove DragonflyDB support which break existing arm64 deployments
- Bundle the `redis-server` using the official Docker image.
- Update all scripts
- Update README
- Remove `libxml2` which was used by DragonflyDB
> Remove support for DragonflyDB

- web/src/routes/+layout.svelte
- web/src/routes/chat/[id]/+page.svelte
The `n_gpu_layers` param was removed by mistake, this PR adds that field again.
Fixes #737
> Add missing gpu_layers param

- README.md
- api/src/serge/data/models.json
Add Neural-Chat  7B-v3.1 
Add OpenChat 3.5-7B
Add OpenLLaMA  3B-v2, 7B-v2, 13B-v2
Add Orca-2 7B, 13B 
Add Starling-LM-7B-Alpha
> Add support for Neural-Chat, OpenChat, Orca 2, and OpenLLaMa v2, Starling LM

- api/src/serge/routers/chat.py
Don't use llama-cpp to verify if model exists. This causes the model to be loaded into memory twice.
> Fix inefficent model check during chat creation

- scripts/deploy.sh
The condition must be true not false to add the support of IPv6.
> Fix ipv6 support conditional check
