serge-chat/serge

api/main.py
api/models.py
api/utils/generate.py
web/src/routes/+page.svelte

- context window size, lets you select how far back the model should consider in its prompt.
- n_threads for multithreading
- init_prompt for customizing the initial prompt before the conversation.

Add support for new parameters in the UI. (thread count, initial prompt, context window size)

---

api/main.py
api/models.py
api/utils/generate.py
web/src/routes/chat/[id]/+page.svelte
web/src/routes/chat/[id]/+page.ts

Answers can have an error now and it gets displayed in the front-end when they do. This will hopefully make debugging easier

errors now surface in the front-end

---

README.md

Hello,
Thanks for the project!
I tried to run locally, and had to make those changes to have it running on Ubuntu 22.04.
I thought I'll make a PR to fix the getting started instructions.

Fix README.md (Getting started commands)

---

.github/workflows/docker-image.yml

Add fix for login-action into ghcr.io

---

Dockerfile

- Update llama.cpp to the latest release: master-5a5f8b1

Update llama.cpp to master-5a5f8b1

---

Dockerfile

- Quick PR to update llama.cpp to master-3525899

Update llama.cpp to master-3525899

---

web/src/routes/chat/[id]/+page.svelte

Tested this and it seems OK.
This allows users to hit CTRL+ENTER to send chat input :)

When a user hits CTRL+ENTER send input

---

.github/workflows/docker-image.yml
Dockerfile
README.md
api/src/serge/dependencies.py
api/src/serge/main.py
api/src/serge/routers/model.py
api/src/serge/utils/convert.py

Update llama.cpp to master-e986f94

---

README.md

- Quick update to README.md to link to `llama.cpp` repo.

Add link to llama.cpp git repo

---

Dockerfile

- Update llama.cpp to `master-437e778` which brings ~10% performance improvements for AVX2

Performance improvements for AVX2 via llama.cpp

---

Dockerfile

- Update llama.cpp tag to master-eeaa7b0

Update llama.cpp to master-eeaa7b0

---

Dockerfile

Update llama.cpp to master-180b693

---

Dockerfile

I may start looking into a way to auto-trigger these PR's :-)

Update llama.cpp to master-be87b6e

---

README.md
api/src/serge/main.py
api/src/serge/utils/generate.py
web/src/app.html
web/src/routes/+page.svelte

Fix LLaMA spelling mistakes

---

.github/workflows/docker-image.yml
.github/workflows/pr-cleanup.yml

- Support for building and publishing PR Docker images, this should ease testing big PR's

Build and publish PR images

---

Dockerfile

Update llama.cpp to master-dcdd65e

---

Dockerfile

Grabbed the wrong tag in the previous PR :-)

Update Dockerfile to fix CI/CD

---

.github/workflows/docker-image.yml
.github/workflows/pr-cleanup.yml
.github/workflows/untagged-cleanup.yml
Dockerfile
README.md
api/poetry.lock
api/pyproject.toml
config/redis.conf
redis.conf

- Use `-slim` images to reduce image size
- Replace `github.actor`
- Condense RUN commands in Dockerfile

Use Debian Slim for base images, Fixes to CI actions

---

.github/workflows/docker-image.yml
.github/workflows/pr-cleanup.yml
.github/workflows/untagged-cleanup.yml

- Added nightly cronjob to delete untagged images
- Changed the logic for detecting when to push an image
- Changed the logic for cleaning PR tagged images after 72hrs

CI Fixes and Updates

---

.github/workflows/pr-cleanup.yml

Trying to get the PR cleanup to work...

Add missing fields to cleanup job

---

api/src/serge/routers/model.py

Updates to Vicuna model names

---

Dockerfile

Expose port 8008 in Dockerfile
Fixes #252

Add EXPOSE in Dockerfile for default server port

---

api/poetry.lock
api/pyproject.toml

Revert "Bump langchain from 0.0.180 to 0.0.184 in /api"

---

api/src/serge/routers/model.py

api\src\serge\routers\model.py:160: error: "object" has no attribute "to_numeric"  [attr-defined]

resolve mypy-error

---

scripts/deploy.sh

Update llama-cpp-python to v0.1.59

---

README.md
api/src/serge/routers/model.py
scripts/deploy.sh

Closes #392
Change all models to the best model of k-quants `q6_K`

Feature: add new k-quants q6_K models

---

api/src/serge/routers/model.py

Fix: models WizardLM-Uncensored-13B file name

---

api/src/serge/models/chat.py
api/src/serge/utils/convert.py
api/src/serge/utils/llm.py
api/src/serge/utils/migrate.py
api/src/serge/utils/stream.py

- Changes based on suggestions from https://github.com/asottile/pyupgrade

Small formatting/typing changes based on pyupgrade

---

README.md
api/src/serge/routers/model.py

modify Airoboros-1.2 for all existing model and  add Airoboros-1.2 65B

Feature: add Airoboros-1.2

---

.github/workflows/model-check.yml

- Added cronjob to check LLM availability on a nightly basis.

Check status of LLM models on a nightly basis

---

.github/workflows/ci.yml
api/src/serge/data/models.json

- Uses github actions to check the syntax of the JSON file used to store the LLM's

Lint the LLM's data JSON file

---

.github/workflows/ci.yml
api/src/serge/schema/schema.json

- Validate the models.json file against a JSON schema

Support for validating models JSON file against a schema

---

scripts/deploy.sh

- Update bindings to 0.1.66
- Add `set -e` to fail script if anything fails to run

Update llama-cpp-python to v0.1.66

---

Dockerfile
Dockerfile.dev
docker-compose.dev.yml
scripts/deploy.sh
scripts/dev.sh

- Added support for dumb-init to forward signals to child processes
- Updated .dev files
- Updated dev.sh and deploy.sh scripts

Fixes to startup scripts and Dockerfiles

---

web/.eslintrc.cjs
web/package-lock.json
web/package.json
web/src/routes/+layout.svelte
web/src/routes/chat/[id]/+page.svelte
web/src/routes/models/+page.svelte
web/svelte.config.js

- Support for svelte v4
- Migrate to eslint-plugin-svelte
- Support for eslint-plugin-vue
Fixes #473

Support for Svelte v4

---

README.md
api/src/serge/data/models.json

Add:
- Orca models
Remove models than don't use alpaca prompt template: 
- Airoboros
- BigTrans
- Guanaco
- Minotour
- Robin
- Tulu
- Vicuna-v1.3
- WizardLM-30B
- Wizard-Vicuna-Uncensored

Add orca and remove models don't use alpaca template

---

Dockerfile
Dockerfile.dev
api/src/serge/models/chat.py
api/src/serge/routers/chat.py
api/src/serge/utils/llm.py
web/src/routes/+page.svelte
web/src/routes/chat/[id]/+page.svelte
web/src/routes/chat/[id]/+page.ts

- Added support for `n_gpu_layers` field in preparation for adding CUDA support
- Added support for `n_gqa` for LLaMA2 support
- Increase Max Tokens to `32k`
- Increase default max_tokens to `2048`
- Increase default Context Window max to 2048

Add support for gpu_layers and LLaMA2 parameters. Increase Token and Context window

---

docker-compose.dev.yml
web/src/routes/+layout.svelte
web/tailwind.config.cjs

Toggle light/dark selector
Fixes #80

Feature: add theme selector light/dark

---

scripts/deploy.sh
scripts/dev.sh

Update llama-cpp-python to v0.1.78

---

README.md
api/src/serge/data/models.json

- Support for WizardCoder-Python-13B-V1.0-GGML
- Removed WizardCoder-Python-30B-V1.0-GGML

Add support for WizardCoder-Python-13B-V1.0-GGML

---

Dockerfile
Dockerfile.dev
api/src/serge/main.py
api/src/serge/routers/ping.py
api/test/healthcheck_models.py

- Add `/api/ping` route. This will return:
```json
{
"message": "pong!"
}
```
- Add `curl` to base images
- Pre-make the following directories: `/data/db` and `/usr/src/app/weights`

Add /ping route to API

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/question.yml
.github/workflows/ci.yml
.github/workflows/docker.yml
.github/workflows/helm-test.yml
.github/workflows/model-check.yml

- Update all the issue templates
- Bump actions/checkout to v4
- Add release-drafter to ignore list for other workflows

Update Issue Templates and workflows

---

api/src/serge/routers/chat.py

fix: Save full text response when using API

---

web/src/routes/chat/[id]/+page.svelte

This pull request addresses a bug in the chat interface related to newline input and ensures that the "Message Serge..." placeholder text appears in the input box after the initial prompt.

Fix newline input bug and display placeholder text in input box

---

api/src/serge/data/models.json

Adding Marx-3B-V2 GGML model

---

.github/release-drafter.yml
.github/workflows/model-check.yml
Dockerfile
Dockerfile.dev
LICENSE
README.md

- Bump debian release to bookworm
- Cleanup README.md
- Fix typo in release-drafter

Add support for latest debian release

---

api/src/serge/models/chat.py
api/src/serge/routers/chat.py
api/src/serge/utils/llm.py
web/src/routes/+layout.svelte
web/src/routes/+page.svelte
web/src/routes/chat/[id]/+page.svelte
web/src/routes/chat/[id]/+page.ts

Dynamically determine how many threads are available for the process and pass those to `llama-cpp`

Add support for using dynamic threads

---

README.md
api/src/serge/data/models.json

- Add TheBloke/vicuna-7B-v1.5-GGUF
- Add TheBloke/vicuna-13B-v1.5-GGUF

Add support for Vicuna 7B and 13B

---

.dockerignore
Dockerfile
Dockerfile.dev
scripts/deploy.sh
scripts/dev.sh
vendor/requirements.txt

- Install llama-cpp-python dependencies during CI
- Update command for installing `llama-cpp-python` wheels

Updates to CI process for Python dependencies

---

.github/release-drafter.yml

Add LLM's section to Release Drafter.

Update release-drafter autolabeler

---

README.md
api/src/serge/data/models.json

- Cleanup some of the names of the models in the `models.json`

Cleanup LLM names

---

README.md
api/src/serge/data/models.json

Add support for Notus LLM

---

README.md
api/src/serge/data/models.json

* Add CodeLlama 7B-Python, 13B-Python and 34B-Python
* Add CodeLlama 13B, 34B, 34B-Instruct
* Update README.md

Updates to CodeLLaMA models

---

README.md
api/src/serge/data/models.json

* Add Vicuna 33B
* Update README

Add Vicuna 33B model

---

README.md
api/src/serge/data/models.json

* Add Vicuna 33B-Coder
* Add LLaMA-2 7B-Coder
* Update README

Add Vicuna 33B-Coder and LLaMA-2 7B-Coder models

---

api/src/serge/routers/model.py
web/src/routes/models/+page.svelte

- Replaced `huggingface_hub.hf_hub_download` with `huggingface_hub.hf_hub_url`.
- Added support for cancelling downloads.
- Refactored the logic for determining models in progress, and downloaded models.
- Fixed issue when displaying the file size of each model.

Refactor of Models API, Support for calling downloads

---

api/src/serge/routers/model.py

- Remove limit for total timeout
- Add 5min timeout for connect
- Add 5min timeout for sock_read

Fix aiohttp timeout settings

---

README.md
api/src/serge/data/models.json

Add support for Phi 2

---

web/package-lock.json
web/package.json
web/svelte.config.js

- Migrate Vite to v5.x
- Migrate SvelteKit to v2
- Migrate Svelte adapters to v2

Migrate to SvelteKit v2

---

api/src/serge/data/models.json

Update OpenChat model version

---

web/src/routes/+page.svelte

Update the information displayed via tooltips

---

web/src/routes/+layout.svelte

Revert "Add support for sidebar menu"

---

web/src/routes/+layout.svelte

Revert "Revert "Add support for sidebar menu""

---

README.md
api/src/serge/data/models.json

Add support for BioMistral 7B
Add support for Nous-Hermes-2-Mistral-7B-DPO
Add support for Nous-Hermes-2-Mixtral-8x7B-DPO
Add support for Nous-Hermes-2-Mixtral-8x7B-SFT
Fixes https://github.com/serge-chat/serge/issues/1155

Add support for BioMistral, Nous-Hermes-2-Mistral and Nous-Hermes-2-Mixtral

---

README.md
api/src/serge/data/models.json

Update Gemma 2B & 7B
Add support for Gemma 2B-Instruct
Add support for Gemma 7B-Instruct

Update Gemma Models

---

api/src/serge/data/models.json

Added Gorilla models to models.json
Fixes #1192

Add Gorilla: Large Language Model 

---

api/src/serge/routers/user.py
api/src/serge/schema/user.py
docker-compose.dev.yml
scripts/dev.sh
web/src/routes/+layout.svelte

- Fix responses from `/api/user` to sanitize `secret`.
- Add missing `--reload` from dev mode
- Improvements to sidebar rendering

fix: Sidebar layout and responses from user api
